---
abstract: 'Yet another perl R interface'
author:
  - 'Aureliano Bombarely'
build_requires:
  Image::Size: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: R::YapRI
provides:
  R::YapRI::Base:
    file: lib/R/YapRI/Base.pm
    version: 0.01
  R::YapRI::Block:
    file: lib/R/YapRI/Block.pm
    version: 0.01
  R::YapRI::Data::Matrix:
    file: lib/R/YapRI/Data/Matrix.pm
    version: 0.01
  R::YapRI::Graph::Simple:
    file: lib/R/YapRI/Graph/Simple.pm
    version: 0.01
  R::YapRI::Interpreter::Perl:
    file: lib/R/YapRI/Interpreter/Perl.pm
    version: 0.01
requires:
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
